### ISSUE TITLE
API endpoint: List commits by time range

### ISSUE THREAD

**Issue by harti2006** [zalando/kontrolletti#128]
Hi,
my plan is to implement a job that verifies if all commits in relevant repositories have messages that contain valid links to the issue tracking system.

To achieve this, I will need two additional parameters for the `/api/hosts/{host}/projects/{project}/repos/{repository}/commits` endpoint, to select only commits made in a certain time range.

My proposal for the swagger definition change:

```yaml
- name: from_date
  in: query
  required: false
  description: "Only commits after this timestamp will be returned"
  type: string
  format: date-time
- name: to_date
  in: query
  required: false
  description: "Only commits before this timestamp will be returned"
  type: string
  format: date-time
```

According to [Swagger 2.0 spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types), timestamps should be in the [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) format.

Pagination parameters and the `is_valid` option should still be available, but `since`and `until` will most likely not be needed by Fullstop anymore.

Best regards,
André
